{% set name = "iterativeWGCNA" %}
{% set version = "1.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1ee490a1b7a0e1164fda08d38053a17f974f82f0237b8c2864bd12a28f3a8efb

build:


  number: 16

  skip: True  # [(win and vc < 14)]
  skip: True  # [(win and py>=38)]
  
requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - pip
    - python
    - r-base
    - r-nlme
    - r-hmisc
    - r-rcpp >=0.11.0
    - r-doparallel
    - r-dynamictreecut >=1.62
    - r-fastcluster
    - r-foreach
    - r-matrixstats >=0.8.1
    - r-survival
  run:
    - matplotlib-base
    - python
    - rpy2  # [not win]
    - rpy2 <3.0  # [win]
    - r-base
    - r-nlme
    - r-hmisc
    - r-rcpp >=0.11.0
    - r-doparallel
    - r-dynamictreecut >=1.62
    - r-fastcluster
    - r-foreach
    - r-matrixstats >=0.8.1
    - r-survival

test:
  imports:
    - iterativeWGCNA
    - iterativeWGCNA.io
    - iterativeWGCNA.r
    - iterativeWGCNA.iterativeWGCNA
  commands:
    - Rscript -e "library('WGCNA')"  # [linux]
    - Rscript.exe -e "library('WGCNA')"  # [win]

  

about:
  home: "http://github.com/cstoeckert/iterativeWGCNA"
  license: "GPL-2.0-only"
  license_family: "GPL"
  license_file: "LICENSE.txt"
  summary: iterativeWGCNA provides a Python-wrapped extension for the R program Weighted 
    Gene Correlation Network Analysis (WGCNA) that improves the robustness of network-based 
    classifications (modules) inferred from whole-transcriptome gene expression datasets.
  doc_url: "https://www.biorxiv.org/content/10.1101/234062v1"

extra:
  recipe-maintainers:
    - thompsonsed
