{% set name = "iterativeWGCNA" %}
{% set version = "1.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1ee490a1b7a0e1164fda08d38053a17f974f82f0237b8c2864bd12a28f3a8efb

build:
  number: 7
  skip: True  # [(win and vc < 14)]
  skip: True  # [(win and py>=38)]
  
requirements:
  build:
    - {{ compiler('c') }}  # [not osx]
    - {{ compiler('cxx') }}  # [not osx]
    - {{ compiler('fortran') }}  # [not osx]
  host:
    - pip
    - python
    - r-base  # [not osx]
    - r-nlme  # [not osx]
    - r-biocmanager
  run:
    - matplotlib
    - python
    - rpy2  # [not win]
    - rpy2 <3.0  # [win]
    - r-base
    - r-nlme
    - r-biocmanager

test:
  imports:
    - iterativeWGCNA
    - iterativeWGCNA.io
    - iterativeWGCNA.r
    - iterativeWGCNA.iterativeWGCNA
  commands:
    - Rscript -e "library('WGCNA')"  # [linux]
    - Rscript.exe -e "library('WGCNA')"  # [win]

  

about:
  home: "http://github.com/cstoeckert/iterativeWGCNA"
  license: "GPL-2.0-only"
  license_family: "GPL"
  license_file: "LICENSE.txt"
  summary: "Iterative application of WGCNA"
  doc_url: "https://www.biorxiv.org/content/10.1101/234062v1"

extra:
  recipe-maintainers:
    - thompsonsed
